/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PolicyRouteImport } from './routes/policy.route'
import { Route as DisclaimerRouteImport } from './routes/disclaimer.route'
import { Route as IndexRouteImport } from './routes/index.route'

// Create/Update Routes

const PolicyRouteRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRoute,
} as any)

const DisclaimerRouteRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRoute
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/disclaimer': typeof DisclaimerRouteRoute
  '/policy': typeof PolicyRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/disclaimer': typeof DisclaimerRouteRoute
  '/policy': typeof PolicyRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteRoute
  '/disclaimer': typeof DisclaimerRouteRoute
  '/policy': typeof PolicyRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disclaimer' | '/policy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disclaimer' | '/policy'
  id: '__root__' | '/' | '/disclaimer' | '/policy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  DisclaimerRouteRoute: typeof DisclaimerRouteRoute
  PolicyRouteRoute: typeof PolicyRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  DisclaimerRouteRoute: DisclaimerRouteRoute,
  PolicyRouteRoute: PolicyRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/disclaimer",
        "/policy"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/disclaimer": {
      "filePath": "disclaimer.route.tsx"
    },
    "/policy": {
      "filePath": "policy.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
