name: build and test on Pull Request
on:
  pull_request:

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      
      - name: Install dependencies
        run: pnpm install


  lint:
    needs: [cache-and-install]
    runs-on: ubuntu-latest
    steps:
      - run: pnpm run lint

  check-type:
    needs: [cache-and-install]
    runs-on: ubuntu-latest
    steps:
      - run: pnpm run check:type

  test:
    needs: [cache-and-install]
    runs-on: ubuntu-latest
    steps:
      - run: pnpm run test

  build:
    needs: [cache-and-install]
    runs-on: ubuntu-latest
    steps:
      - run: pnpm build