name: build and test on Pull Request
on:
  pull_request:

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: lint
        run: pnpm run lint
      - name: check-type
        run: pnpm run check:type
      - name: test
        run: pnpm run test
      - name: build-check
        run: pnpm run build